config/routes.rb
Rails.application.routes.draw do

  resources :worker_planifications
  resources :permission_histories
  resources :vacations, only: [:new, :edit, :update, :destroy, :create]
  resources :workers, except: [:index]
  mount RailsAdmin::Engine => '/administracion', as: 'rails_admin'
  resources :history_credits do
    collection { post :report }
    collection { post :store }
    collection { get :monitoreo }
    collection { post :eliminar }
  end

  resources :pending_trials, only: [:index, :show, :destroy, :new, :create]
  resources :insolvencies
  resources :insolvency_activities
  resources :insolvency_stages
  resources :without_goods
  resources :without_good_activities
  resources :withoutgood_stages
  resources :goods
  resources :good_activities
  resources :good_stages
  resources :lawyers
  resources :discarded_trials, only:[:destroy] do
    collection {post :ingresar}
  end
  devise_for :users, controllers: {
      sessions: 'authentication/sessions',
      registrations: 'authentication/registrations'
  }

  authenticated :user do
    root to: "main#dashboard", as: :authenticated_root
  end

  root to: "main#home"
  # Ruta para la busqueda de un juicio
  get '/juicios/search', to: "main#search", as: :search_juicios
  # Pantalla principal del modulo de juicios
  get 'home_creditos', to: "main#home_creditos", as: :creditos_root
  # Ruta de la pantalla para la gestion de etapas
  get '/list/stages', to: "main#stage", as: :stages_root
  # CPantalla donde se muestran los nuevos creditos de la base de datos Oracle
  get '/creditos/new', to: "main#new_trial", as: :new_trials_root
  # Ruta de la pantalla de evaluacion de resultados
  get '/evaluacion_resultados', to: "main#evaluacion_resultados", as: :evaluacion_resultados
  # Ruta del controlador para crear un pending_trial
  post '/creditos/create', to: "main#create_trial", as: :create_trial_root
  # Ruta para actualizar el estado de un juicio
  post '/juicio/:id/update', to: "main#change_state", as: :update_trial_state
  # Ruta para manejar los reingresos de juicios
  post '/reingresos/:id', to: "main#reingresos", as: :reingreso_juicios
  #   Ruta que muestra todos los juicios
  get '/juicios', to: 'main#listado_juicios', as: :listado_juicios
  # Ruta del metodo para cambiar un juicio de bienes a sin bienes y al contrario
  post '/juicio/update', to: "main#change_trial_type", as: :cambiar_tipo_juicio



  #   Modulo de creditos
  get '/credits', to: 'credits#index', as: :credits_root

  namespace :credits do
    post 'creditos_por_vencer'
    post 'creditos_vencidos'
    post 'creditos_concedidos'
    post 'cosechas'
    post 'matrices'
    post 'cartera_recuperada'
    post 'indicadores_creditos_vigentes'
    post 'indicadores_creditos_colocados'
  end

  # Medulo de Agencias
  get '/agencias', to: 'agencias#index', as: :agencias_root
  namespace :agencias do
    post 'indicadores_financieros'
    post 'indicadores_seps'
  end

  # Medulo de Desemponio Social
  get '/desempenio_social', to: 'desempenio_social#index', as: :desempenio_social_root
  namespace :desempenio_social do
    post 'balance_social'
  end

  # Modulo de Recursos Humanos
  get '/recursos_humanos', to: 'recursos_humanos#index', as: :recursos_humanos_root
  namespace :recursos_humanos do
    get 'vacaciones'
    post 'guardar_historial'
    get 'planificacion_general'
  end
end

app/models/insolvency.rb
# == Schema Information
#
# Table name: insolvencies
#
#  id                      :integer          not null, primary key
#  credit_id               :string
#  socio_id                :string
#  nombres                 :string
#  cedula                  :string
#  telefono                :string
#  celular                 :string
#  direccion               :string
#  sector                  :string
#  parroquia               :string
#  canton                  :string
#  nombre_grupo            :string
#  grupo_solidario         :string
#  sucursal                :string
#  oficial_credito         :string
#  cartera_heredada        :string
#  fecha_concesion         :string
#  fecha_vencimiento       :string
#  tipo_garantia           :string
#  garantia_real           :string
#  garantia_fiduciaria     :string
#  dir_garante             :string
#  tel_garante             :string
#  valor_cartera_castigada :string
#  bienes                  :string
#  tipo_credito            :string
#  insolvency_stage_id     :integer
#  insolvency_activity_id  :integer
#  estado                  :string
#  observaciones           :text
#  juicio_id               :string
#  fentrega_juicios        :date
#  fcalificacion_juicio    :date
#  codigo_juicio           :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  lawyer_id               :integer
#  fecha_terminacion       :string
#  fecha_original_juicio   :date
#  nom_garante1            :string
#  ci_garante_1            :string
#  cony_garante1           :string
#  nom_garante2            :string
#  ci_garante2             :string
#  cony_garante2           :string
#  propietario_bienes      :string
#  calificacion            :string
#  user_id                 :integer
#  valor_avaluo_comercial  :string
#  valor_avaluo_catastral  :string
#  avaluo_titulo           :string
#  interes                 :string
#  mora                    :string
#  gastos_judiciales       :string
#

class Insolvency < ApplicationRecord
  searchkick
  belongs_to :insolvency_stage
  belongs_to :insolvency_activity
  belongs_to :lawyer
  belongs_to :user

  # Scopes
  scope :activos, -> { where(estado: "Activo") }
  scope :cancelados, -> { where(estado: "Cancelado") }
  scope :reingresos, -> { where(estado: "Reingreso") }
  scope :terminados, -> { where(estado: "Terminado") }
  scope :insolvencias, -> { where(estado: "Insolvencia") }
  scope :reestructurados, -> { where(estado: "Reestructurado") }
  scope :abandonados, -> { where(estado: "Abandono") }
  scope :ultimos, ->{ order("created_at DESC")}

  scope :activados, ->{ where(estado: ["Activo", "Reingreso", "Insolvencia", "Reestructurado"])}
  scope :sin_reestructurados, -> { where(estado: ["Activo", "Reingreso", "Insolvencia"]) }

  def etapa_estimada
    fecha_inicio = self.created_at.to_date
    dias_transcurridos = (Date.current - fecha_inicio)

    # Compara que el # de días transcurridos estén entre el # días de inicio y fin de cada etapa
    if dias_transcurridos >= ((fecha_inicio + 8.month) - fecha_inicio).to_i
      "Notificación de quiebra"
    elsif dias_transcurridos >= ((fecha_inicio + 7.month) - fecha_inicio).to_i and dias_transcurridos <= ((fecha_inicio + 8.month) - fecha_inicio).to_i
      "Síndico de quiebra"
    elsif dias_transcurridos >= ((fecha_inicio + 4.month) - fecha_inicio).to_i and dias_transcurridos <= ((fecha_inicio + 7.month) - fecha_inicio).to_i
      "Notificación pública"
    elsif dias_transcurridos >= ((fecha_inicio + 3.month) - fecha_inicio).to_i and dias_transcurridos <= ((fecha_inicio + 4.month) - fecha_inicio).to_i
      "Citaciones finalizadas"
    elsif dias_transcurridos >= ((fecha_inicio + 1.month) - fecha_inicio).to_i and dias_transcurridos <= ((fecha_inicio + 3.month) - fecha_inicio).to_i
      "Acta de sorteo judicial"
    else
      "Mandamiento de ejecución"
    end

  end

  def semaforo
    # Alamacenará la fecha de la etapa estimada del credito
    fecha_etapa_estimada = ''

    # Almacenará la fecha de la proxima etapa la que viene despues de la estimada
    fecha_proxima_etapa = ''

    # Almacena el numero de mes de la etapa
    mes = self.insolvency_stage.months.to_i

    # Almacena la fecha de la etapa actual en la que se encuentra el juicio
    fecha_etapa_actual = (self.created_at + mes.month).to_date

    nombre_etapa_estimada = self.etapa_estimada
    case nombre_etapa_estimada
      when "Mandamiento de ejecución"
        fecha_etapa_estimada = self.created_at
        fecha_proxima_etapa =  self.created_at + 1.month
      when "Acta de sorteo judicial"
        fecha_etapa_estimada = self.created_at + 1.month
        fecha_proxima_etapa =  self.created_at + 3.month
      when "Citaciones finalizadas"
        fecha_etapa_estimada = self.created_at + 3.month
        fecha_proxima_etapa =  self.created_at + 4.month
      when "Notificación pública"
        fecha_etapa_estimada = self.created_at + 4.month
        fecha_proxima_etapa =  self.created_at + 7.month
      when "Síndico de quiebra"
        fecha_etapa_estimada = self.created_at + 7.month
        fecha_proxima_etapa =  self.created_at + 8.month
      when "Notificación de quiebra"
        return ["terminado", "label label-default"]

    end
    # Si las etapas son iguales quiere decir que solo va a poder estar en rojo
    # o amarillo segun los días transcurrido entre las etapas
    if self.insolvency_stage.name == nombre_etapa_estimada
      # Dias que han pasado desde la etapa hasta ahora
      dias_transcurridos = (Date.current - fecha_etapa_estimada.to_date).to_i
      # Dias totales que existe entre etapa y etapa para poder sacar el 25%
      dias_proxima_etapa = (fecha_proxima_etapa.to_date - fecha_etapa_estimada.to_date)
      # Quiere decir que aún no ha pasado o ya pasó los 0.4 días
      if dias_transcurridos <= (dias_proxima_etapa * 0.4).to_i
        ["verde", "label label-success"]
      else
        ["amarillo", "label label-warning"]
      end
    else # Si las etapas son diferentes quiere decir que o está atrasado o estado adelantado
      # Días que han pasado desde la fecha que empieza la etapa hasta ahora
      # si es negativo quiere decir que esta adelantado y se encuentra en una etapa a futuro
      dias_transcurridos_desde_etapa_actual = (Date.current - fecha_etapa_actual).to_i

      # Almacena los días que hay desde etapa actual hasta la estimada si es negativo
      # quiere decir que se encuentra  adelantado entre etapas
      dias_entre_etapas = (fecha_etapa_estimada.to_date - fecha_etapa_actual).to_i

      # Si los días que han transcurrido son mayores al numero total de días entre las etapas es
      # porque esta trasado una etapa, se valida que sean positivos porque cuando son negativos
      # quiere decir que esta adelantado
      if ( dias_transcurridos_desde_etapa_actual >= dias_entre_etapas) and dias_entre_etapas > 0
        ["rojo", "label label-danger"]
      else
        ["verde", "label label-success"]
      end
    end
  end

  def self.buscar_por_idCredito id
    Insolvency.find_by(:credit_id => id)
  end


end

app/controllers/insolvencies_controller.rb
class InsolvenciesController < ApplicationController
  before_action :set_insolvency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin, only: [:index, :edit, :new, :destroy]

  # GET /insolvencies
  # GET /insolvencies.json
  def index
    @insolvencies = Insolvency.all
  end

  # GET /insolvencies/1
  # GET /insolvencies/1.json
  def show
    # Recupera los datos variables de este id de credito desde la bdd Oracle
    # Filtro la letra "R" al principio de credit_id para saber  si el juicio
    # tiene un id de reingreso y busque las variables
    id = @insolvency.credit_id
    if id[0] == "R" or id[0] == "I"
      id = id[2..id.length]
    end
    @variables = Oracledb.getSaldos(id)
    @semaforo_actual = @insolvency.semaforo
  end

  # GET /insolvencies/new
  def new
    @insolvency = Insolvency.new
  end

  # GET /insolvencies/1/edit
  def edit
  end

  # POST /insolvencies
  # POST /insolvencies.json
  def create
    @insolvency = Insolvency.new(insolvency_params)

    respond_to do |format|
      if @insolvency.save
        format.html { redirect_to @insolvency, notice: 'Insolvency was successfully created.' }
        format.json { render :show, status: :created, location: @insolvency }
      else
        format.html { render :new }
        format.json { render json: @insolvency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insolvencies/1
  # PATCH/PUT /insolvencies/1.json
  def update
    respond_to do |format|
      if @insolvency.update(insolvency_params)
        format.html { redirect_to @insolvency, notice: 'Insolvency was successfully updated.' }
        format.json { render :show, status: :ok, location: @insolvency }
      else
        format.html { render :edit }
        format.json { render json: @insolvency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insolvencies/1
  # DELETE /insolvencies/1.json
  def destroy
    @insolvency.destroy
    respond_to do |format|
      format.html { redirect_to insolvencies_url, notice: 'Insolvency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insolvency
      @insolvency = Insolvency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insolvency_params
      params.require(:insolvency).permit(:credit_id, :socio_id, :nombres, :cedula, :telefono, :celular, :direccion, :sector, :parroquia, :canton, :nombre_grupo, :grupo_solidario, :sucursal, :oficial_credito, :cartera_heredada, :fecha_concesion, :fecha_vencimiento, :tipo_garantia, :garantia_real, :garantia_fiduciaria, :dir_garante, :tel_garante, :valor_cartera_castigada, :bienes, :tipo_credito, :insolvency_stage_id, :insolvency_activity_id, :estado, :observaciones, :juicio_id, :fentrega_juicios, :fcalificacion_juicio, :codigo_juicio, :lawyer_id)
    end

    def set_layout
      return "creditos_judiciales" if action_name == "show"
      super
    end
end

app/helpers/insolvencies_helper.rb
module InsolvenciesHelper
end

app/views/insolvencies/_form.html.haml
= form_for @insolvency do |f|
  - if @insolvency.errors.any?
    #error_explanation
      %h2= "#{pluralize(@insolvency.errors.count, "error")} prohibited this insolvency from being saved:"
      %ul
        - @insolvency.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :credit_id
    = f.text_field :credit_id
  .field
    = f.label :socio_id
    = f.text_field :socio_id
  .field
    = f.label :nombres
    = f.text_field :nombres
  .field
    = f.label :cedula
    = f.text_field :cedula
  .field
    = f.label :telefono
    = f.text_field :telefono
  .field
    = f.label :celular
    = f.text_field :celular
  .field
    = f.label :direccion
    = f.text_field :direccion
  .field
    = f.label :sector
    = f.text_field :sector
  .field
    = f.label :parroquia
    = f.text_field :parroquia
  .field
    = f.label :canton
    = f.text_field :canton
  .field
    = f.label :nombre_grupo
    = f.text_field :nombre_grupo
  .field
    = f.label :grupo_solidario
    = f.text_field :grupo_solidario
  .field
    = f.label :sucursal
    = f.text_field :sucursal
  .field
    = f.label :oficial_credito
    = f.text_field :oficial_credito
  .field
    = f.label :cartera_heredada
    = f.text_field :cartera_heredada
  .field
    = f.label :fecha_concesion
    = f.text_field :fecha_concesion
  .field
    = f.label :fecha_vencimiento
    = f.text_field :fecha_vencimiento
  .field
    = f.label :tipo_garantia
    = f.text_field :tipo_garantia
  .field
    = f.label :garantia_real
    = f.text_field :garantia_real
  .field
    = f.label :garantia_fiduciaria
    = f.text_field :garantia_fiduciaria
  .field
    = f.label :dir_garante
    = f.text_field :dir_garante
  .field
    = f.label :tel_garante
    = f.text_field :tel_garante
  .field
    = f.label :valor_cartera_castigada
    = f.text_field :valor_cartera_castigada
  .field
    = f.label :bienes
    = f.text_field :bienes
  .field
    = f.label :tipo_credito
    = f.text_field :tipo_credito
  .field
    = f.label :insolvency_stage
    = f.text_field :insolvency_stage
  .field
    = f.label :insolvency_activity
    = f.text_field :insolvency_activity
  .field
    = f.label :estado
    = f.text_field :estado
  .field
    = f.label :observaciones
    = f.text_area :observaciones
  .field
    = f.label :juicio_id
    = f.text_field :juicio_id
  .field
    = f.label :fentrega_juicios
    = f.date_select :fentrega_juicios
  .field
    = f.label :fcalificacion_juicio
    = f.date_select :fcalificacion_juicio
  .field
    = f.label :codigo_juicio
    = f.text_field :codigo_juicio
  .actions
    = f.submit 'Save'

app/views/insolvencies/edit.html.haml
%h1 Editing insolvency

= render 'form'

= link_to 'Show', @insolvency
\|
= link_to 'Back', insolvencies_path

app/views/insolvencies/index.html.haml
%h1 Listing insolvencies

%table
  %thead
    %tr
      %th Credit
      %th Socio
      %th Nombres
      %th Cedula
      %th Telefono
      %th Celular
      %th Direccion
      %th Sector
      %th Parroquia
      %th Canton
      %th Nombre grupo
      %th Grupo solidario
      %th Sucursal
      %th Oficial credito
      %th Cartera heredada
      %th Fecha concesion
      %th Fecha vencimiento
      %th Tipo garantia
      %th Garantia real
      %th Garantia fiduciaria
      %th Dir garante
      %th Tel garante
      %th Valor cartera castigada
      %th Bienes
      %th Tipo credito
      %th Insolvency stage
      %th Insolvency activity
      %th Estado
      %th Observaciones
      %th Juicio
      %th Fentrega juicios
      %th Fcalificacion juicio
      %th Codigo juicio
      %th
      %th
      %th

  %tbody
    - @insolvencies.each do |insolvency|
      %tr
        %td= insolvency.credit_id
        %td= insolvency.socio_id
        %td= insolvency.nombres
        %td= insolvency.cedula
        %td= insolvency.telefono
        %td= insolvency.celular
        %td= insolvency.direccion
        %td= insolvency.sector
        %td= insolvency.parroquia
        %td= insolvency.canton
        %td= insolvency.nombre_grupo
        %td= insolvency.grupo_solidario
        %td= insolvency.sucursal
        %td= insolvency.oficial_credito
        %td= insolvency.cartera_heredada
        %td= insolvency.fecha_concesion
        %td= insolvency.fecha_vencimiento
        %td= insolvency.tipo_garantia
        %td= insolvency.garantia_real
        %td= insolvency.garantia_fiduciaria
        %td= insolvency.dir_garante
        %td= insolvency.tel_garante
        %td= insolvency.valor_cartera_castigada
        %td= insolvency.bienes
        %td= insolvency.tipo_credito
        %td= insolvency.insolvency_stage
        %td= insolvency.insolvency_activity
        %td= insolvency.estado
        %td= insolvency.observaciones
        %td= insolvency.juicio_id
        %td= insolvency.fentrega_juicios
        %td= insolvency.fcalificacion_juicio
        %td= insolvency.codigo_juicio
        %td= link_to 'Show', insolvency
        %td= link_to 'Edit', edit_insolvency_path(insolvency)
        %td= link_to 'Destroy', insolvency, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Insolvency', new_insolvency_path

app/views/insolvencies/new.html.haml
%h1 New insolvency

= render 'form'

= link_to 'Back', insolvencies_path

app/views/insolvencies/show.html.haml
%h3.text-center.big-top-space
  Datos del credito
  %small= @insolvency.credit_id
  %small
    %span.label{class: "#{@semaforo_actual[1]}"}
      = @semaforo_actual[0]
%h5.text-center
  Juicio
  %small= @insolvency.estado
.row.center-xs
  .col-xs-11
    = img_juicio @insolvency.insolvency_stage.name, 'insolvencias'
    = render partial: "partials/creditos/buttons_states", locals: {tipo: "insolvencia", trial: @insolvency} if current_user.permissions == 5

.row.center-xs.middle-xs.top-space
  .col-xs-11
    .tabbable
      %ul.nav.nav-tabs.nav-append-content
        %li.active
          %a{href: "#tab1"}Datos del Crédito
        %li
          %a{href: "#tab2"}Datos de la Socia(o)
        %li
          %a{href: "#tab3"}Saldos
        %li
          %a{href: "#tab4"}Datos Judiciales
        %li
          %a{href: "#tab5"}Detalles
        %li
          %a{href: "#tab6"}Garantes
        %li
          %a{href: "#tab7"}Observaciones
      .tab-content

        .tab-pane.active{id: "tab1"}
          %h4.text-center Datos del Credito
          %hr
          .row.text-left
            .col-xs-6
              %p
                %b.text-primary Id Credito:
                = @insolvency.credit_id
              %p
                %b.text-primary Id Socio:
                = @insolvency.socio_id
              %p
                %b.text-primary Nombre grupo:
                = @insolvency.nombre_grupo
              %p
                %b.text-primary Grupo solidario:
                = @insolvency.grupo_solidario
              %p
                %b.text-primary Propietario de los bienes:
                = @insolvency.propietario_bienes
              %p
                %b.text-primary Fecha del juicio:
                = @insolvency.created_at

            .col-xs-6
              %p
                %b.text-primary Bienes:
                = @insolvency.bienes
              %p
                %b.text-primary Tipo credito:
                = @insolvency.tipo_credito
              %p
                %b.text-primary Etapa:
                = @insolvency.insolvency_stage.name
              %p
                %b.text-primary Proceso:
                = @insolvency.insolvency_activity.name
              %p
                %b.text-primary Estado:
                = @insolvency.estado
              %p
                %b.text-primary Fecha original del juicio:
                = @insolvency.fecha_original_juicio


        .tab-pane{id: "tab2"}
          %h4.text-center Datos de la Socia(o)
          %hr
          .row.text-left
            .col-xs-6
              %p
                %b.text-primary Nombres:
                = @insolvency.nombres
              %p
                %b.text-primary Cedula:
                = @insolvency.cedula
              %p
                %b.text-primary Telefono:
                = @variables["telefono"]
              %p
                %b.text-primary Celular:
                = @variables["celular"]

            .col-xs-6
              %p
                %b.text-primary Direccion:
                = @variables["direccion"]
              %p
                %b.text-primary Sector:
                = @variables["sector"]
              %p
                %b.text-primary Parroquia:
                = @variables["parroquia"]
              %p
                %b.text-primary Canton:
                = @variables["canton"]
              %p
                %b.text-primary Sucursal:
                = @insolvency.sucursal


        .tab-pane{id: "tab3"}
          %h4.text-center Datos Crediticios
          %hr
          .row.text-left
            .col-xs-4
              %p
                %b.text-primary Monto real:
                = @variables["monto_real"]
              %p
                %b.text-primary Saldo total:
                = @variables["saldo_total"]
              %p
                %b.text-primary Valor cancela:
                = @variables["valor_cancela"]
              %p
                %b.text-primary Gastos extra judiciales:
                = @variables["gastos_extra_judicial"]
              %p
                %b.text-primary Valor Judicial:
                = @variables["valor_judicial"]
            .col-xs-4
              %p
                %b.text-primary Días de mora:
                = @variables["diasmora_pd"]
              %p
                %b.text-primary Provisión requerida:
                = @variables["provision_requerida"]
              %p
                %b.text-primary Calificación propia:
                = @variables["calificacion_propia"]
              %p
                %b.text-primary Demanda Judicial:
                = @variables["demanda_judicial"]
            .col-xs-4
              %p
                %b.text-primary Interés:
                = @variables["interes"]
              %p
                %b.text-primary Mora:
                = @variables["mora"]
              %p
                %b.text-primary Gasto judiciales:
                = @variables["gastos_judiciales"]
              %p
                %b.text-primary Total Adeudado:
                = @variables["total_adeudado"]


        .tab-pane{id: "tab4"}
          %h4.text-center Datos Judiciales
          %hr
          .row.text-left
            - if current_user.permissions == 4
              .col-xs-6
                %p
                  %b.text-primary Abogado
                  = best_in_place(@insolvency, :lawyer_id, :as => :select, collection: Lawyer.collection)
                %p
                  %b.text-primary Juicio:
                  = best_in_place @insolvency, :juicio_id
                %p
                  %b.text-primary Fecha entrega de juicio:
                  = best_in_place @insolvency, :fentrega_juicios, as: :date
              .col-xs-6
                %p
                  %b.text-primary Fecha calificacion de juicio:
                  = best_in_place @insolvency, :fcalificacion_juicio, as: :date
                %p
                  %b.text-primary Codigo juicio:
                  = best_in_place @insolvency, :codigo_juicio
            - else
              .col-xs-6
                %p
                  %b.text-primary Abogado
                  = @insolvency.lawyer.full_name
                %p
                  %b.text-primary Juicio:
                  = @insolvency.juicio_id
                %p
                  %b.text-primary Fecha entrega de juicio:
                  = @insolvency.fentrega_juicios.strftime('%B %d, del %Y') if @insolvency.fentrega_juicios
              .col-xs-6
                %p
                  %b.text-primary Fecha calificación de juicio:
                  = @insolvency.fcalificacion_juicio.strftime('%B %d, del %Y') if @insolvency.fcalificacion_juicio
                %p
                  %b.text-primary Codigo juicio:
                  = @insolvency.codigo_juicio


        .tab-pane{id: "tab5"}
          %h4.text-center Datos Extras
          %hr
          .row.text-left
            .col-xs-4
              %p
                %b.text-primary Oficial credito:
                = @insolvency.oficial_credito
              %p
                %b.text-primary Cartera heredada:
                = @insolvency.cartera_heredada
              %p
                %b.text-primary Fecha concesion:
                = @insolvency.fecha_concesion
              %p
                %b.text-primary Fecha vencimiento:
                = @insolvency.fecha_vencimiento
            .col-xs-4
              %p
                %b.text-primary Tipo garantia:
                = @insolvency.tipo_garantia
              %p
                %b.text-primary Garantia real:
                = @insolvency.garantia_real
              %p
                %b.text-primary Garantia fiduciaria:
                = @insolvency.garantia_fiduciaria
              %p
                %b.text-primary Valor cartera castigada:
                = @insolvency.valor_cartera_castigada
            .col-xs-4
              %p
                %b.text-primary Valor avalúo comercial:
                = @variables["valor_avaluo_comercial"]
              %p
                %b.text-primary Valor avalúo catastral:
                = @variables["valor_avaluo_catastral"]
              %p
                %b.text-primary Avalúo título:
                = @variables["avaluo_titulo"]



        .tab-pane{id: "tab6"}
          %h4.text-center Datos de los Garantes
          %hr
          .row.text-left
            .col-xs-4
              %p
                %b.text-primary Nombres Garante 1:
                = @insolvency.nom_garante1
              %p
                %b.text-primary Cédula Garante 1:
                = @insolvency.ci_garante_1
              %p
                %b.text-primary Cony Garante 1:
                = @insolvency.cony_garante1
            .col-xs-4
              %p
                %b.text-primary Nombres Garante 2:
                = @insolvency.nom_garante2
              %p
                %b.text-primary Cédula Garante 2:
                = @insolvency.ci_garante2
              %p
                %b.text-primary Cony Garante 2:
                = @insolvency.cony_garante2
            .col-xs-4
              %p
                %b.text-primary Dirección garante:
                = @variables["dir_garante"]
              %p
                %b.text-primary Teléfono garante:
                = @variables["tel_garante"]

        .tab-pane{id: "tab7"}
          .row
            - if current_user.permissions == 4
              .col-xs-10.start-xs.top-space
                %h4.text-center Observaciones
                %p.text-left
                  = best_in_place @insolvency, :observaciones, :as => :textarea
            - else
              .col-xs-10.start-xs.top-space
                %h4.text-center Observaciones
                %p.text-left= @insolvency.observaciones