config/routes.rb
Rails.application.routes.draw do

  resources :worker_planifications
  resources :permission_histories
  resources :vacations, only: [:new, :edit, :update, :destroy, :create]
  resources :workers, except: [:index]
  mount RailsAdmin::Engine => '/administracion', as: 'rails_admin'
  resources :history_credits do
    collection { post :report }
    collection { post :store }
    collection { get :monitoreo }
    collection { post :eliminar }
  end

  resources :pending_trials, only: [:index, :show, :destroy, :new, :create]
  resources :insolvencies
  resources :insolvency_activities
  resources :insolvency_stages
  resources :without_goods
  resources :without_good_activities
  resources :withoutgood_stages
  resources :goods
  resources :good_activities
  resources :good_stages
  resources :lawyers
  resources :discarded_trials, only:[:destroy] do
    collection {post :ingresar}
  end
  devise_for :users, controllers: {
      sessions: 'authentication/sessions',
      registrations: 'authentication/registrations'
  }

  authenticated :user do
    root to: "main#dashboard", as: :authenticated_root
  end

  root to: "main#home"
  # Ruta para la busqueda de un juicio
  get '/juicios/search', to: "main#search", as: :search_juicios
  # Pantalla principal del modulo de juicios
  get 'home_creditos', to: "main#home_creditos", as: :creditos_root
  # Ruta de la pantalla para la gestion de etapas
  get '/list/stages', to: "main#stage", as: :stages_root
  # CPantalla donde se muestran los nuevos creditos de la base de datos Oracle
  get '/creditos/new', to: "main#new_trial", as: :new_trials_root
  # Ruta de la pantalla de evaluacion de resultados
  get '/evaluacion_resultados', to: "main#evaluacion_resultados", as: :evaluacion_resultados
  # Ruta del controlador para crear un pending_trial
  post '/creditos/create', to: "main#create_trial", as: :create_trial_root
  # Ruta para actualizar el estado de un juicio
  post '/juicio/:id/update', to: "main#change_state", as: :update_trial_state
  # Ruta para manejar los reingresos de juicios
  post '/reingresos/:id', to: "main#reingresos", as: :reingreso_juicios
  #   Ruta que muestra todos los juicios
  get '/juicios', to: 'main#listado_juicios', as: :listado_juicios
  # Ruta del metodo para cambiar un juicio de bienes a sin bienes y al contrario
  post '/juicio/update', to: "main#change_trial_type", as: :cambiar_tipo_juicio



  #   Modulo de creditos
  get '/credits', to: 'credits#index', as: :credits_root

  namespace :credits do
    post 'creditos_por_vencer'
    post 'creditos_vencidos'
    post 'creditos_concedidos'
    post 'cosechas'
    post 'matrices'
    post 'cartera_recuperada'
    post 'indicadores_creditos_vigentes'
    post 'indicadores_creditos_colocados'
  end

  # Medulo de Agencias
  get '/agencias', to: 'agencias#index', as: :agencias_root
  namespace :agencias do
    post 'indicadores_financieros'
    post 'indicadores_seps'
  end

  # Medulo de Desemponio Social
  get '/desempenio_social', to: 'desempenio_social#index', as: :desempenio_social_root
  namespace :desempenio_social do
    post 'balance_social'
  end

  # Modulo de Recursos Humanos
  get '/recursos_humanos', to: 'recursos_humanos#index', as: :recursos_humanos_root
  namespace :recursos_humanos do
    get 'vacaciones'
    post 'guardar_historial'
    get 'planificacion_general'
  end
end

app/models/vacation.rb
# == Schema Information
#
# Table name: vacations
#
#  id                :integer          not null, primary key
#  worker_id         :integer
#  fecha_permiso     :date
#  descripcion       :string
#  horas             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  fecha_terminacion :date
#

class Vacation < ApplicationRecord
  belongs_to :worker
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :set_vacation, only: [:show, :edit, :update, :destroy]
  before_action :set_worker, only: [:new]
  before_action :authenticate_user!
  before_action :authenticate_permissions

  # GET /vacations
  # GET /vacations.json
  def index
    @vacations = Vacation.all
  end

  # GET /vacations/1
  # GET /vacations/1.json
  def show
  end

  # GET /vacations/new
  def new
    @vacation = @worker.vacations.new
    @vacation.worker_id = params[:id]
  end

  # GET /vacations/1/edit
  def edit
  end

  # POST /vacations
  # POST /vacations.json
  def create
    @vacation = Vacation.new(vacation_params)
    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation.worker, notice: 'Permiso creado satisfactoriamente!' }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacations/1
  # PATCH/PUT /vacations/1.json
  def update
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation.worker, notice: 'Permiso actualizado satisfactoriamente!' }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    worker = @vacation.worker
    @vacation.destroy
    respond_to do |format|
      format.html { redirect_to worker, notice: 'Vacation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
    end

    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_params
      params.require(:vacation).permit(:worker_id, :fecha_permiso, :descripcion, :horas, :fecha_terminacion)
    end

    def set_layout
      return "recursos_humanos"
    end

    def authenticate_permissions
      unless current_user.permissions == 10 || current_user.permissions == 9 || current_user.permissions == 3
        redirect_to root_path, notice: "No estas autorizado!"
      end
    end
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_form.html.haml
= form_for @vacation do |f|
  - if @vacation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vacation.errors.count, "error")} prohibited this vacation from being saved:"
      %ul
        - @vacation.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.hidden_field :worker_id
  .form-group
    %p.text-left.color-blue
      %b Fecha de Inicio
    .input-group
      %span.input-group-btn
        %button{class:"btn", type:"button"}
          Calendario
      = text_field "vacation", :fecha_permiso, class:"form-control datepick", id: "datepicker1"

  .form-group
    %p.text-left.color-blue
      %b Fecha de Fin
    .input-group
      %span.input-group-btn
        %button{class:"btn", type:"button"}
          Calendario
      = text_field "vacation", :fecha_terminacion, class:"form-control datepick", id: "datepicker2"
  .form-group
    %p.text-left.color-blue
      %b Descripción
    = f.text_area :descripcion, class: "form-control"
  .form-group
    %p.text-left.color-blue
      %b Número de Horas
    = f.text_field :horas, class: "form-control"

  .form-group
    = f.submit 'Enviar', class: "btn btn-success"

app/views/vacations/edit.html.haml
.row
  .col-xs-11.col-md-6.col-md-offset-3
    %h4.text-primary= "Editar permiso del empleado #{@vacation.worker.fullname}"

    = render 'form'

.row.center-xs
  .col-xs-12
    = link_to 'Regresar', @vacation.worker, class: "btn btn-hg btn-info"

app/views/vacations/index.html.haml
%h1 Listing vacations

%table
  %thead
    %tr
      %th Worker
      %th Fecha permiso
      %th Descripcion
      %th Horas
      %th
      %th
      %th

  %tbody
    - @vacations.each do |vacation|
      %tr
        %td= vacation.worker
        %td= vacation.fecha_permiso
        %td= vacation.descripcion
        %td= vacation.horas
        %td= link_to 'Show', vacation
        %td= link_to 'Edit', edit_vacation_path(vacation)
        %td= link_to 'Destroy', vacation, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Vacation', new_vacation_path

app/views/vacations/new.html.haml
.row
  .col-xs-11.col-md-6.col-md-offset-3
    %h4.text-primary= "Ingresar permiso para #{@worker.fullname}"
    = render 'form'

.row.center-xs
  .col-xs-12
    = link_to 'Regresar', @worker, class: "btn btn-info"

app/views/vacations/show.html.haml
%p#notice= notice

%p
  %b Worker:
  = @vacation.worker
%p
  %b Fecha permiso:
  = @vacation.fecha_permiso
%p
  %b Descripcion:
  = @vacation.descripcion
%p
  %b Horas:
  = @vacation.horas

= link_to 'Edit', edit_vacation_path(@vacation)
\|
= link_to 'Back', vacations_path