config/routes.rb
Rails.application.routes.draw do

  resources :worker_planifications
  resources :permission_histories
  resources :vacations, only: [:new, :edit, :update, :destroy, :create]
  resources :workers, except: [:index]
  mount RailsAdmin::Engine => '/administracion', as: 'rails_admin'
  resources :history_credits do
    collection { post :report }
    collection { post :store }
    collection { get :monitoreo }
    collection { post :eliminar }
  end

  resources :pending_trials, only: [:index, :show, :destroy, :new, :create]
  resources :insolvencies
  resources :insolvency_activities
  resources :insolvency_stages
  resources :without_goods
  resources :without_good_activities
  resources :withoutgood_stages
  resources :goods
  resources :good_activities
  resources :good_stages
  resources :lawyers
  resources :discarded_trials, only:[:destroy] do
    collection {post :ingresar}
  end
  devise_for :users, controllers: {
      sessions: 'authentication/sessions',
      registrations: 'authentication/registrations'
  }

  authenticated :user do
    root to: "main#dashboard", as: :authenticated_root
  end

  root to: "main#home"
  # Ruta para la busqueda de un juicio
  get '/juicios/search', to: "main#search", as: :search_juicios
  # Pantalla principal del modulo de juicios
  get 'home_creditos', to: "main#home_creditos", as: :creditos_root
  # Ruta de la pantalla para la gestion de etapas
  get '/list/stages', to: "main#stage", as: :stages_root
  # CPantalla donde se muestran los nuevos creditos de la base de datos Oracle
  get '/creditos/new', to: "main#new_trial", as: :new_trials_root
  # Ruta de la pantalla de evaluacion de resultados
  get '/evaluacion_resultados', to: "main#evaluacion_resultados", as: :evaluacion_resultados
  # Ruta del controlador para crear un pending_trial
  post '/creditos/create', to: "main#create_trial", as: :create_trial_root
  # Ruta para actualizar el estado de un juicio
  post '/juicio/:id/update', to: "main#change_state", as: :update_trial_state
  # Ruta para manejar los reingresos de juicios
  post '/reingresos/:id', to: "main#reingresos", as: :reingreso_juicios
  #   Ruta que muestra todos los juicios
  get '/juicios', to: 'main#listado_juicios', as: :listado_juicios
  # Ruta del metodo para cambiar un juicio de bienes a sin bienes y al contrario
  post '/juicio/update', to: "main#change_trial_type", as: :cambiar_tipo_juicio



  #   Modulo de creditos
  get '/credits', to: 'credits#index', as: :credits_root

  namespace :credits do
    post 'creditos_por_vencer'
    post 'creditos_vencidos'
    post 'creditos_concedidos'
    post 'cosechas'
    post 'matrices'
    post 'cartera_recuperada'
    post 'indicadores_creditos_vigentes'
    post 'indicadores_creditos_colocados'
  end

  # Medulo de Agencias
  get '/agencias', to: 'agencias#index', as: :agencias_root
  namespace :agencias do
    post 'indicadores_financieros'
    post 'indicadores_seps'
  end

  # Medulo de Desemponio Social
  get '/desempenio_social', to: 'desempenio_social#index', as: :desempenio_social_root
  namespace :desempenio_social do
    post 'balance_social'
  end

  # Modulo de Recursos Humanos
  get '/recursos_humanos', to: 'recursos_humanos#index', as: :recursos_humanos_root
  namespace :recursos_humanos do
    get 'vacaciones'
    post 'guardar_historial'
    get 'planificacion_general'
  end
end

app/models/history_credit.rb
# == Schema Information
#
# Table name: history_credits
#
#  id           :integer          not null, primary key
#  credit_id    :string
#  socio_id     :string
#  cedula       :string
#  agencia      :string
#  abogado      :string
#  asesor       :string
#  estado       :string
#  semaforo     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  mes          :string
#  tipo_credito :string
#  user_id      :integer
#

class HistoryCredit < ApplicationRecord
  # Me permite recuperar unicamente el historial entre las fechas dadas
  # la variable fechas es un array
  scope :filtrado, ->(fechas) { where(mes: fechas) }
  scope :verdes, ->{ where(estado: "Verde") }
  scope :amarillos, ->{ where(estado: "Amarillo") }
  scope :rojos, ->{ where(estado: "Rojo") }
  scope :activos, ->{ where(estado: "Activo") }

  scope :abogado, ->(nombres){where("abogado LIKE ?", "%#{nombres}%")}
  scope :agencia, ->(agencia){where("agencia LIKE ?", "#{agencia}")}
  scope :asesor, ->(asesor){where("asesor LIKE ?", "#{asesor}")}

  scope :asesores_cobranzas, ->(id){where(user_id: id)}

  # Recibe un id_credito, un mes y todos los datos
  # y regresa el valor del semaforo
  def self.buscar_fecha(id_credito, fecha, datos)
    datos.each do | row |
      if row.credit_id == id_credito && row.mes == fecha
        return row.semaforo
      end
    end
    return nil
  end

  # Buscara en los historiales de credito si un credito terminado, abandonado o terminado ya se ingreso
  # para no ingresarlo dos veces
  def self.buscar_creditos_finalizados(credit_id)
    results = HistoryCredit.where(credit_id: credit_id).where(estado: ["Terminado", "Abandono", "Cancelado"])
    if results.present?
       results
    else
       nil
    end
  end

  def self.obtener_fechas_guardadas
    HistoryCredit.distinct.pluck(:mes)
  end

  def self.obtener_agencias
    HistoryCredit.distinct.pluck(:agencia)
  end

  def self.obtener_asesores
    HistoryCredit.distinct.pluck(:asesor)
  end

end

app/controllers/history_credits_controller.rb
class HistoryCreditsController < ApplicationController
  before_action :set_history_credit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_gerente, only: [:eliminar]
  before_action :authenticate_user!
  before_action :authenticate_jcreditos, only: [:monitoreo, :store]
  before_action :authenticate_admin, only: [:index, :show, :new, :edit]

  def monitoreo
    @goods = Good.includes(:good_stage)
    @withoutgoods = WithoutGood.includes(:withoutgood_stage)
    @insolvencies = Insolvency.includes(:insolvency_stage)
    @fechas = HistoryCredit.obtener_fechas_guardadas
  end

  # Visualiza el historial de creditos
  def report
      if params["inicio"] == "" or params["fin"] == ""
        redirect_to creditos_root_path, notice: "Debes seleccionar dos fechas!"
        return false
      end

      fechainicio = params["inicio"]
      @inicio = fechainicio.to_date

      fechafin = params["fin"]
      @fin = fechafin.to_date

      # Guardo en un array los meses con los anios que queremos buscar
      @arreglo = extraer_fechas_entre(@inicio, @fin)

      @original = HistoryCredit.filtrado(@arreglo)

      if params["lawyer"].present?

        id_asesor = params[:user]["user_id"]
        if params["lawyer"]["full_name"] == ""; abogado = "%%" else abogado = params["lawyer"]["full_name"] end
        if params["asesores"] == ""; asesor = "%%" else asesor = params["asesores"] end
        if params["agencia"] == ""; agencia = "%%" else agencia = params["agencia"] end

        if id_asesor != ''
          @original = HistoryCredit.filtrado(@arreglo).abogado(abogado).asesor(asesor).agencia(agencia).asesores_cobranzas(id_asesor)
        else
          @original = HistoryCredit.filtrado(@arreglo).abogado(abogado).asesor(asesor).agencia(agencia)
        end

        @history_credits = @original.group(:credit_id, :id)

        if agencia == "%%"; agencia = "Todos" else agencia end
        if abogado == "%%"; abogado = "Todos" else abogado end
        if asesor == "%%"; asesor = "Todos" else agencia end

        if id_asesor != ''
          @filtros = {asesor: asesor, abogado: abogado, agencia: agencia, asesores_cobranzas: User.find(id_asesor).full_name}
        else
          @filtros = {asesor: asesor, abogado: abogado, agencia: agencia}
        end
      else
        @original = HistoryCredit.filtrado(@arreglo)
        @history_credits = @original.group(:credit_id, :id)
      end


  end

  # Metodo que guardar en la base de datos el historial de creditos
  def store
    @goods = Good.includes(:lawyer)
    @withoutgoods = WithoutGood.includes(:lawyer)
    @insolvencies = Insolvency.includes(:lawyer)

    date = 1.month.ago.strftime('%m-%Y')
    @goods.each do |credit|
      # Cancelados, abandonos
      if credit.estado == "Terminado" or credit.estado == "Abandono" or credit.estado == "Cancelado" or credit.estado == "Reestructurado"
        result = HistoryCredit.buscar_creditos_finalizados credit.credit_id
        if result.present?

        else
          semaforo = credit.semaforo
          HistoryCredit.create(credit_id: credit.credit_id, socio_id: credit.socio_id, cedula: credit.cedula, agencia: credit.sucursal, abogado: credit.lawyer.full_name, asesor: credit.oficial_credito, mes: date, estado: credit.estado, semaforo: semaforo[0], user_id: credit.user_id, tipo_credito: "bienes")

        end
      else
        semaforo = credit.semaforo
        HistoryCredit.create(credit_id: credit.credit_id, socio_id: credit.socio_id, cedula: credit.cedula, agencia: credit.sucursal, abogado: credit.lawyer.full_name, asesor: credit.oficial_credito, mes: date, estado: credit.estado, semaforo: semaforo[0], user_id: credit.user_id, tipo_credito: "bienes")
      end

    end

    @withoutgoods.each do |credit|
      if credit.estado == "Terminado" or credit.estado == "Abandono" or credit.estado == "Cancelado" or credit.estado == "Reestructurado"
        result = HistoryCredit.buscar_creditos_finalizados credit.credit_id
        if result.present?

        else
          semaforo = credit.semaforo
          HistoryCredit.create(credit_id: credit.credit_id, socio_id: credit.socio_id, cedula: credit.cedula, agencia: credit.sucursal, abogado: credit.lawyer.full_name, asesor: credit.oficial_credito, mes: date, estado: credit.estado, semaforo: semaforo[0], user_id: credit.user_id, tipo_credito: "sinbienes")
        end
      else
        semaforo = credit.semaforo
        HistoryCredit.create(credit_id: credit.credit_id, socio_id: credit.socio_id, cedula: credit.cedula, agencia: credit.sucursal, abogado: credit.lawyer.full_name, asesor: credit.oficial_credito, mes: date, estado: credit.estado, semaforo: semaforo[0], user_id: credit.user_id, tipo_credito: "sinbienes")

      end
    end

    @insolvencies.each do |credit|
      if credit.estado == "Terminado" or credit.estado == "Abandono" or credit.estado == "Cancelado" or credit.estado == "Reestructurado"
        result = HistoryCredit.buscar_creditos_finalizados credit.credit_id
        if result.present?

        else
          semaforo = credit.semaforo
          HistoryCredit.create(credit_id: credit.credit_id, socio_id: credit.socio_id, cedula: credit.cedula, agencia: credit.sucursal, abogado: credit.lawyer.full_name, asesor: credit.oficial_credito, mes: date, estado: credit.estado, semaforo: semaforo[0], user_id: credit.user_id, tipo_credito: "insolvencia")
        end
      else
        semaforo = credit.semaforo
        HistoryCredit.create(credit_id: credit.credit_id, socio_id: credit.socio_id, cedula: credit.cedula, agencia: credit.sucursal, abogado: credit.lawyer.full_name, asesor: credit.oficial_credito, mes: date, estado: credit.estado, semaforo: semaforo[0], user_id: credit.user_id, tipo_credito: "insolvencia")

      end
    end

    respond_to do |format|
      format.html { redirect_to monitoreo_history_credits_path, notice: "Monitoreo guardado!" }
    end
  end

  # Elimina to-do el historial de creditos de una fecha dada
  def eliminar
    fecha = params[:fecha]
    HistoryCredit.find_by(mes: fecha)
    respond_to do |format|
      if HistoryCredit.where(mes: fecha).destroy_all
        format.html { redirect_to creditos_root_path, notice: "Se realizó la petición correctamente!" }
      else
        format.html { redirect_to creditos_root_path, alert: "Algo salio mal! Intentalo de nuevo"}
      end
    end
  end



  # GET /history_credits
  # GET /history_credits.json
  def index
    @history_credits = HistoryCredit.all
  end

  # GET /history_credits/1
  # GET /history_credits/1.json
  def show

  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "No debes recargar esta página"
    redirect_to root_path
  end

  # GET /history_credits/new
  def new
    @history_credit = HistoryCredit.new
  end

  # GET /history_credits/1/edit
  def edit
  end

  # POST /history_credits
  # POST /history_credits.json
  def create
    @history_credit = HistoryCredit.new(history_credit_params)

    respond_to do |format|
      if @history_credit.save
        format.html { redirect_to @history_credit, notice: 'History credit was successfully created.' }
        format.json { render :show, status: :created, location: @history_credit }
      else
        format.html { render :new }
        format.json { render json: @history_credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /history_credits/1
  # PATCH/PUT /history_credits/1.json
  def update
    respond_to do |format|
      if @history_credit.update(history_credit_params)
        format.html { redirect_to @history_credit, notice: 'History credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @history_credit }
      else
        format.html { render :edit }
        format.json { render json: @history_credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /history_credits/1
  # DELETE /history_credits/1.json
  def destroy
    @history_credit.destroy
    respond_to do |format|
      format.html { redirect_to history_credits_url, notice: 'History credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history_credit
      @history_credit = HistoryCredit.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to creditos_root_path, notice: "No debes recargar esta página"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_credit_params
      params.require(:history_credit).permit(:credit_id, :socio_id, :cedula, :agencia, :abogado, :asesor, :estado, :semaforo)
    end

    # Convierte los paramatros(anio, mes, dia) a un tipo fecha 2017-03-25
    def convertir_fechas(anio, mes, dia)
      fecha = Date.new anio.to_i, mes.to_i, dia.to_i
    end

    # Extrae los meses-anios de las fechas de inicio y fin que se envian
    # por parametros y devulve un array ['07-2017', '09-2017']
    def extraer_fechas_entre(inicio, fin)
      arr = Array.new
      (inicio.year..fin.year).each do |y|
        mo_start = (inicio.year == y) ? inicio.month : 1
        mo_end = (fin.year == y) ? fin.month : 12


        (mo_start..mo_end).each do |m|
          fecha = Date.new(y,m,1).strftime('%m-%Y').to_s
          arr.push(fecha)
        end
      end
      arr
    end

    def set_layout
      return "creditos_judiciales" if action_name == "monitoreo" or action_name == "report"
    end

    def authenticate_gerente
      if current_user.permissions != 3
        redirect_to root_path, alert: "No estas autorizado"
        return false
      end
    end
end

app/views/history_credits/_form.html.haml
= form_for @history_credit do |f|
  - if @history_credit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@history_credit.errors.count, "error")} prohibited this history_credit from being saved:"
      %ul
        - @history_credit.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :credit_id
    = f.text_field :credit_id
  .field
    = f.label :socio_id
    = f.text_field :socio_id
  .field
    = f.label :cedula
    = f.text_field :cedula
  .field
    = f.label :agencia
    = f.text_field :agencia
  .field
    = f.label :abogado
    = f.text_field :abogado
  .field
    = f.label :asesor
    = f.text_field :asesor
  .field
    = f.label :estado
    = f.text_field :estado
  .field
    = f.label :semaforo
    = f.text_field :semaforo
  .actions
    = f.submit 'Save'

app/views/history_credits/edit.html.haml
%h1 Editing history_credit

= render 'form'

= link_to 'Show', @history_credit
\|
= link_to 'Back', history_credits_path

app/views/history_credits/index.html.haml
%h1 Listing history_credits

%table
  %thead
    %tr
      %th Credit
      %th Socio
      %th Cedula
      %th Agencia
      %th Abogado
      %th Asesor
      %th Estado
      %th Semaforo
      %th
      %th
      %th

  %tbody
    - @history_credits.each do |history_credit|
      %tr
        %td= history_credit.credit_id
        %td= history_credit.socio_id
        %td= history_credit.cedula
        %td= history_credit.agencia
        %td= history_credit.abogado
        %td= history_credit.asesor
        %td= history_credit.estado
        %td= history_credit.semaforo
        %td= link_to 'Show', history_credit
        %td= link_to 'Edit', edit_history_credit_path(history_credit)
        %td= link_to 'Destroy', history_credit, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New History credit', new_history_credit_path

app/views/history_credits/monitoreo.haml
%ul.breadcrumb.big-top-space
  %li
    = link_to "Dashboard", root_path
  %li
    = link_to "Home", creditos_root_path
  %li.active
    Monitoreo

.row.center-xs
  .col-xs-11
    %h2{data: {toggle: "tooltip", tooltip: {style:"light"}, placement: "bottom" }, title:"Recuerda que se guardará el historial con fecha del mes anterior"}
      Monitoreo mensual de créditos
  .col-xs-11
    = link_to "Guardar monitoreo mensual", store_history_credits_path, method: :post, class: "btn btn-wide btn-danger", data: {confirm: "Estás segur@?"}
  .col-xs-11
    %h3{data: {toggle: "tooltip", tooltip: {style:"light"}, placement: "top" }, title:"Aquí te mostramos las fechas de los historiales que ya han sido guardados"}
      Historial de guardado
    %ul{class: "nav nav-list nav-list-vivid"}
      - if @fechas.empty?
        %li Todavía no tienes historiales guardados
      - else
        - @fechas.each do |fecha|
          %li= fecha

%h3.text-center.text-muted Juicios con Bienes
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Etapa Actual
            %th Estado
            %th Semaforo
            %th Ver
        %tbody
          - @goods.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.good_stage.name
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", good_path(trial), class: "btn btn-inverse"

%h3.text-center.text-muted Juicios sin Bienes
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Etapa Actual
            %th Estado
            %th Semaforo
            %th Ver
        %tbody
          - @withoutgoods.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.withoutgood_stage.name
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", without_good_path(trial), class: "btn btn-inverse"


%h3.text-center.text-muted Juicios de Insolvencia
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Etapa Actual
            %th Estado
            %th Semaforo
            %th Ver
        %tbody
          - @insolvencies.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.insolvency_stage.name
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", insolvency_path(trial), class: "btn btn-inverse"

app/views/history_credits/new.html.haml
%h1 New history_credit

= render 'form'

= link_to 'Back', history_credits_path

app/views/history_credits/report.haml
%ul.breadcrumb.big-top-space
  %li
    = link_to "Dashboard", root_path
  %li
    = link_to "Home", creditos_root_path
  %li.active
    Historial de semaforos

%h2.text-center Reporte de juicios
.row.center-xs
  .col-xs-11
    %button{class:"btn btn-inverse", type:"button", data: {toggle:"collapse", target: "#collapseExample"}, aria: {expanded:"false", controls: "collapseExample"}}
      Buscar nuevas fechas
  .col-xs-5.bottom-space
    .collapse.top-space#collapseExample
      .well
        = render "partials/reports/form_report"
  .col-xs-11
    .dialog
      .container
        = form_tag report_history_credits_path, class: "form-inline" do
          .col-xs-12
            .form-group
              %label Abogados
              = collection_select(:lawyer, :full_name, Lawyer.all, :name, :full_name, prompt: "Todos", class: "form-control")
          .col-xs-12
            .form-group
              %label Agencias
              = select_tag("agencia", options_for_select(HistoryCredit.obtener_agencias), prompt: "Todos")
          .col-xs-12
            .form-group
              %label Asesores
              = select_tag("asesores", options_for_select(HistoryCredit.obtener_asesores), prompt: "Todos")
          .col-xs-12
            .form-group
              %label Asesor C.
              = collection_select(:user, :user_id, User.where(permissions: 4), :id, :full_name, prompt: "Todos", class: "form-control")



          = hidden_field_tag "inicio", @inicio
          = hidden_field_tag "fin", @fin
          .col-xs-12
          = submit_tag "Filtrar", class: "btn btn-wide btn-primary"
        - unless @filtros.nil?
          .col-xs-5
            %h5 Filtros aplicados
            %p.text-left
              Abogado
              %b= @filtros[:abogado]
            %p.text-left
              Agencia
              %b= @filtros[:agencia]
            %p.text-left
              Asesor
              %b= @filtros[:asesor]
            %p.text-left
              Asesor
              %b= @filtros[:asesores_cobranzas]



    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Ver
            %th Cedula
            %th Id Crédito
            %th Id Socio
            %th Estado
            - @arreglo.each do |fecha|
              %th= fecha
        %tbody
          - verdes = 0
          - amarillos = 0
          - rojos = 0
          - terminados = 0
          - total = 0
          - @history_credits.each do |history_credit|
            %tr
              - if history_credit.tipo_credito == "bienes"
                %th
                  - good_temp = Good.buscar_por_idCredito history_credit.credit_id
                  - unless good_temp.nil?
                    = link_to "Ver", good_path(good_temp), class: "btn btn-inverse", target: :_blank
              - elsif history_credit.tipo_credito == "sinbienes"
                %th
                  - without_good_temp = WithoutGood.buscar_por_idCredito history_credit.credit_id
                  - unless without_good_temp.nil?
                    = link_to "Ver", without_good_path(without_good_temp), class: "btn btn-inverse", target: :_blank
              - else
                %th
                  - insolvency_temp = Insolvency.buscar_por_idCredito history_credit.credit_id
                  - unless insolvency_temp.nil?
                    = link_to "Ver", insolvency_path(insolvency_temp), class: "btn btn-inverse", target: :_blank
              %td= history_credit.cedula
              %td= history_credit.credit_id
              %td= history_credit.socio_id
              %th= history_credit.estado

              - @arreglo.each do |fecha|

                - dato = HistoryCredit.buscar_fecha(history_credit.credit_id, fecha, @original)
                - if dato.nil?
                  %td -
                - else
                  - if dato == "rojo"
                    - rojos += 1
                    %th
                      %span.label.label-danger= dato
                  - elsif dato == "verde"
                    - verdes += 1
                    %th
                      %span.label.label-success= dato
                  - elsif dato == "amarillo"
                    - amarillos += 1
                    %th
                      %span.label.label-warning= dato
                  - elsif dato == "terminado"
                    - terminados += 1
                    %th
                      %span.label.label-default= dato
                  - total += 1

.row.center-xs
  .col-xs-11
    .col-xs-3
      %h5.text-primary Porcentaje de semaforos Verdes
      - if total > 0
        - porcentaje = (verdes * 100)/total
      %p
        %b= porcentaje.to_s + "%"
    .col-xs-3
      %h5.text-primary Porcentaje de semaforos Amarillos
      - if total > 0
        - porcentaje = (amarillos * 100)/total
      %p
        %b= porcentaje.to_s + "%"
    .col-xs-3
      %h5.text-primary Pocentaje de semaforos Rojos
      - if total > 0
        - porcentaje = (rojos * 100)/total
      %p
        %b= porcentaje.to_s + "%"
    .col-xs-3
      %h5.text-primary Semaforos Terminados
      - if total > 0
        - porcentaje = (terminados * 100)/total
      %p
        %b= porcentaje.to_s + "%"

.row.center-xs
  .col-xs-11
    %h3 % de Semaforos por Meses
    - @arreglo.each do |fecha|
      - datos = HistoryCredit.filtrado(fecha)
      - ver = 0
      - ama = 0
      - roj = 0
      - ter = 0
      - tot = 0
      - datos.each do |credit|
        - if credit.semaforo == "rojo"
          - roj += 1
        - elsif credit.semaforo == "amarillo"
          - ama += 1
        - elsif credit.semaforo == "verde"
          - ver += 1
        - elsif credit.semaforo == "terminado"
          - ter += 1
        - tot += 1
      .col-xs-4
        .card.bg-color-white.padding.bottom-space
          %h5.text-primary
            Mes:
            = fecha
          - if tot > 0
            - porcentaje = (ver * 100)/tot
            %p
              Verdes:
              %b= porcentaje.to_s + "%"

            - porcentaje = (ama * 100)/tot
            %p
              Amarillos:
              %b= porcentaje.to_s + "%"

            - porcentaje = (roj * 100)/tot
            %p
              Rojos:
              %b= porcentaje.to_s + "%"

            - porcentaje = (ter * 100)/tot
            %p
              Terminados:
              %b= porcentaje.to_s + "%"

.row.center-xs
  .col-xs-11
    %h3 Este reporte se extrajo de las fechas
  .col-xs-6.top-space
    %ul{class: "nav nav-list nav-list-vivid"}
      - @arreglo.each do |fecha|
        %li= fecha

app/views/history_credits/show.html.haml
%p#notice= notice

%p
  %b Credit:
  = @history_credit.credit_id
%p
  %b Socio:
  = @history_credit.socio_id
%p
  %b Cedula:
  = @history_credit.cedula
%p
  %b Agencia:
  = @history_credit.agencia
%p
  %b Abogado:
  = @history_credit.abogado
%p
  %b Asesor:
  = @history_credit.asesor
%p
  %b Estado:
  = @history_credit.estado
%p
  %b Semaforo:
  = @history_credit.semaforo

= link_to 'Edit', edit_history_credit_path(@history_credit)
\|
= link_to 'Back', history_credits_path