config/routes.rb
Rails.application.routes.draw do

  resources :worker_planifications
  resources :permission_histories
  resources :vacations, only: [:new, :edit, :update, :destroy, :create]
  resources :workers, except: [:index]
  mount RailsAdmin::Engine => '/administracion', as: 'rails_admin'
  resources :history_credits do
    collection { post :report }
    collection { post :store }
    collection { get :monitoreo }
    collection { post :eliminar }
  end

  resources :pending_trials, only: [:index, :show, :destroy, :new, :create]
  resources :insolvencies
  resources :insolvency_activities
  resources :insolvency_stages
  resources :without_goods
  resources :without_good_activities
  resources :withoutgood_stages
  resources :goods
  resources :good_activities
  resources :good_stages
  resources :lawyers
  resources :discarded_trials, only:[:destroy] do
    collection {post :ingresar}
  end
  devise_for :users, controllers: {
      sessions: 'authentication/sessions',
      registrations: 'authentication/registrations'
  }

  authenticated :user do
    root to: "main#dashboard", as: :authenticated_root
  end

  root to: "main#home"
  # Ruta para la busqueda de un juicio
  get '/juicios/search', to: "main#search", as: :search_juicios
  # Pantalla principal del modulo de juicios
  get 'home_creditos', to: "main#home_creditos", as: :creditos_root
  # Ruta de la pantalla para la gestion de etapas
  get '/list/stages', to: "main#stage", as: :stages_root
  # CPantalla donde se muestran los nuevos creditos de la base de datos Oracle
  get '/creditos/new', to: "main#new_trial", as: :new_trials_root
  # Ruta de la pantalla de evaluacion de resultados
  get '/evaluacion_resultados', to: "main#evaluacion_resultados", as: :evaluacion_resultados
  # Ruta del controlador para crear un pending_trial
  post '/creditos/create', to: "main#create_trial", as: :create_trial_root
  # Ruta para actualizar el estado de un juicio
  post '/juicio/:id/update', to: "main#change_state", as: :update_trial_state
  # Ruta para manejar los reingresos de juicios
  post '/reingresos/:id', to: "main#reingresos", as: :reingreso_juicios
  #   Ruta que muestra todos los juicios
  get '/juicios', to: 'main#listado_juicios', as: :listado_juicios
  # Ruta del metodo para cambiar un juicio de bienes a sin bienes y al contrario
  post '/juicio/update', to: "main#change_trial_type", as: :cambiar_tipo_juicio



  #   Modulo de creditos
  get '/credits', to: 'credits#index', as: :credits_root

  namespace :credits do
    post 'creditos_por_vencer'
    post 'creditos_vencidos'
    post 'creditos_concedidos'
    post 'cosechas'
    post 'matrices'
    post 'cartera_recuperada'
    post 'indicadores_creditos_vigentes'
    post 'indicadores_creditos_colocados'
  end

  # Medulo de Agencias
  get '/agencias', to: 'agencias#index', as: :agencias_root
  namespace :agencias do
    post 'indicadores_financieros'
    post 'indicadores_seps'
  end

  # Medulo de Desemponio Social
  get '/desempenio_social', to: 'desempenio_social#index', as: :desempenio_social_root
  namespace :desempenio_social do
    post 'balance_social'
  end

  # Modulo de Recursos Humanos
  get '/recursos_humanos', to: 'recursos_humanos#index', as: :recursos_humanos_root
  namespace :recursos_humanos do
    get 'vacaciones'
    post 'guardar_historial'
    get 'planificacion_general'
  end
end

app/views/partials/creditos/_buttons_states.haml
.nav.nav-pills.top-space
  %li= link_to "Terminado", update_trial_state_path(:id => trial.id, :tipo_juicio => tipo, :state => 'Terminado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
  %li= link_to "Abandono", update_trial_state_path(:id => trial.id, :tipo_juicio => tipo, :state => 'Abandono'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
  %li= link_to "Cancelar", update_trial_state_path(:id => trial.id, :tipo_juicio => tipo, :state => 'Cancelado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
  %li= link_to "Reestructurado", update_trial_state_path(:id => trial.id, :tipo_juicio => tipo, :state => 'Reestructurado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
  %li= link_to "Activar", update_trial_state_path(:id => trial.id, :tipo_juicio => tipo, :state => 'Activo'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
  - if trial.estado == "Reestructurado"
    %li= link_to "Reingresar", reingreso_juicios_path(:id => trial.id, :tipo_juicio => tipo, :estado => 'Reestructurado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} unless trial.estado == 'Reingreso'
  - else
    %li= link_to "Reingresar", reingreso_juicios_path(:id => trial.id, :tipo_juicio => tipo), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} unless trial.estado == 'Reingreso'
  - if tipo == "bienes"
    %li= link_to "Convertir a Sin Bienes", cambiar_tipo_juicio_path(estado_actual: tipo,juicio: trial.id), method: :post, data: {confirm: "Estás segur@?"}
  - elsif tipo == "sinbienes"
    %li= link_to "Convertir a Bienes", cambiar_tipo_juicio_path(estado_actual: tipo, juicio: trial.id), method: :post, data: {confirm: "Estás segur@?"}
    %li= link_to "Insolvencia", update_trial_state_path(:id => trial.id, :tipo_juicio => 'envio_insolvencia'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} if is_last_stage? trial.withoutgood_stage.name

app/views/partials/creditos/_jcobranzas_home_tables.haml
%ul.breadcrumb.big-top-space
  %li
    = link_to "Dashboard", root_path
  %li
    = link_to "Home", creditos_root_path

.row.center-xs
  .col-xs-11.top-space
    %button{class:"btn btn-inverse", type:"button", data: {toggle:"collapse", target: "#collapseExample"}, aria: {expanded:"false", controls: "collapseExample"}}
      Historial de semaforización
  .col-xs-5
    .collapse.top-space#collapseExample
      .well
        = render "partials/reports/form_report"
%h3.text-center.text-muted Juicios con Bienes

.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Socio
            %th Id Juicio
            %th Cédula
            %th Etapa Actual
            %th Proceso
            %th Estado
            %th Semaforo
            %th Acciones
        %tbody
          - @conBienes.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.socio_id
              %td.table-width= trial.juicio_id
              %td= trial.cedula
              %td= best_in_place(trial, :good_stage_id, :as => :select, collection: GoodStage.collection)
              %td= best_in_place(trial, :good_activity_id, :as => :select, collection: trial.good_stage.get_activities)
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", good_path(trial), class: "btn btn-inverse"
              %td= link_to "Terminar", update_trial_state_path(:id => trial.id, :tipo_juicio => 'bienes', :state => 'Terminado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} if is_last_stage? trial.good_stage.name

%h3.text-center.text-muted Juicios sin Bienes
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Socio
            %th Id Juicio
            %th Cédula
            %th Etapa Actual
            %th Proceso
            %th Estado
            %th Semaforo
            %th Acciones
        %tbody
          - @sinBienes.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.socio_id
              %td= trial.juicio_id
              %td= trial.cedula
              %td= best_in_place(trial, :withoutgood_stage_id, :as => :select, collection: WithoutgoodStage.collection)
              %td= best_in_place(trial, :without_good_activity_id, :as => :select, collection: trial.withoutgood_stage.get_activities)
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", without_good_path(trial), class: "btn btn-inverse"


%h3.text-center.text-muted Juicios de Insolvencia
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Socio
            %th Id Juicio
            %th Cédula
            %th Etapa Actual
            %th Proceso
            %th Estado
            %th Semaforo
            %th Acciones
        %tbody
          - @insolvencias.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.socio_id
              %td= trial.juicio_id
              %td= trial.cedula
              %td= best_in_place(trial, :insolvency_stage_id, :as => :select, collection: InsolvencyStage.collection)
              %td= best_in_place(trial, :insolvency_activity_id, :as => :select, collection: trial.insolvency_stage.get_activities)
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", insolvency_path(trial), class: "btn btn-inverse"
              %td= link_to "Terminar", update_trial_state_path(:id => trial.id, :tipo_juicio => 'insolvencia', :state => 'Terminado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} if is_last_stage? trial.insolvency_stage.name

app/views/partials/creditos/_jcreditos_home_tables.haml
%ul.breadcrumb.big-top-space
  %li
    = link_to "Dashboard", root_path
  %li.active
    Home
.row.center-xs
  .col-xs-11.top-space
    %button{class:"btn btn-inverse", type:"button", data: {toggle:"collapse", target: "#collapseExample"}, aria: {expanded:"false", controls: "collapseExample"}}
      Historial de semaforización
  .col-xs-5
    .collapse.top-space#collapseExample
      .well
        = render "partials/reports/form_report"

%h3.text-center.text-muted Juicios con Bienes

.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Cédula
            %th Etapa Actual
            %th Etapa Estimada
            %th Estado
            %th Semaforo
            %th Ver
        %tbody
          - @conBienes.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.cedula
              %td= trial.good_stage.name
              %td= trial.etapa_estimada
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", good_path(trial), class: "btn btn-inverse"
              %td= link_to "Terminar", update_trial_state_path(:id => trial.id, :tipo_juicio => 'bienes', :state => 'Terminado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
              %td= link_to "Reingresar", reingreso_juicios_path(:id => trial.id, :tipo_juicio => "bienes"), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} unless trial.estado == 'Reingreso'

%h3.text-center.text-muted Juicios sin Bienes
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Cédula
            %th Etapa Actual
            %th Etapa Estimada
            %th Estado
            %th Semaforo
            %th
            %th
        %tbody
          - @sinBienes.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.cedula
              %td= trial.withoutgood_stage.name
              %td= trial.etapa_estimada
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", without_good_path(trial), class: "btn btn-inverse"
              %td= link_to "Terminar", update_trial_state_path(:id => trial.id, :tipo_juicio => 'sinbienes', :state => 'Terminado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
              %td= link_to "Reingresar", reingreso_juicios_path(:id => trial.id, :tipo_juicio => "sinbienes"), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} unless trial.estado == 'Reingreso'
              %th= link_to "Insolvencia", update_trial_state_path(:id => trial.id, :tipo_juicio => 'envio_insolvencia'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} if is_last_stage? trial.withoutgood_stage.name

%h3.text-center.text-muted Juicios de Insolvencia
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Cédula
            %th Etapa Actual
            %th Etapa Estimada
            %th Estado
            %th Semaforo
            %th Ver
            %th
        %tbody
          - @insolvencias.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.cedula
              %td= trial.insolvency_stage.name
              %td= trial.etapa_estimada
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", insolvency_path(trial), class: "btn btn-inverse"
              %td= link_to "Terminar", update_trial_state_path(:id => trial.id, :tipo_juicio => 'insolvencia', :state => 'Terminado'), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"}
              %td= link_to "Reingresar", reingreso_juicios_path(:id => trial.id, :tipo_juicio => "insolvencia"), method: :post, class: "btn btn-inverse", data: {confirm: "Estás segur@?"} unless trial.estado == 'Reingreso'

app/views/partials/creditos/_list_all_trials.haml
.row.center-xs
  .col-xs-11.top-space
    %button{class:"btn btn-inverse", type:"button", data: {toggle:"collapse", target: "#collapseExample"}, aria: {expanded:"false", controls: "collapseExample"}}
      Historial de Semaforos
  .col-xs-5
    .collapse.top-space#collapseExample
      .well
        = render "partials/reports/form_report"

%h3.text-center.text-muted Juicios con Bienes

.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Id Juicio
            %th Cédula
            %th Etapa Actual
            %th Actividad
            %th Etapa Estimada
            %th Estado
            %th Semaforo
            %th Ver
        %tbody
          - @conBienes.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.juicio_id
              %td= trial.cedula
              %td= best_in_place_if(trial.user == current_user, trial, :good_stage_id, :as => :select, collection: GoodStage.collection)
              %td= best_in_place_if(trial.user == current_user, trial, :good_activity_id, :as => :select, collection: trial.good_stage.get_activities)
              %td= trial.etapa_estimada
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", good_path(trial), class: "btn btn-inverse"

%h3.text-center.text-muted Juicios sin Bienes
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Id Juicio
            %th Cédula
            %th Etapa Actual
            %th Actividad
            %th Etapa Estimada
            %th Estado
            %th Semaforo
            %th
            %th
        %tbody
          - @sinBienes.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.juicio_id
              %td= trial.cedula
              %td= best_in_place_if(trial.user == current_user, trial, :withoutgood_stage_id, :as => :select, collection: WithoutgoodStage.collection)
              %td= best_in_place_if(trial.user == current_user, trial, :without_good_activity_id, :as => :select, collection: trial.withoutgood_stage.get_activities)
              %td= trial.etapa_estimada
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", without_good_path(trial), class: "btn btn-inverse"


%h3.text-center.text-muted Juicios de Insolvencia
.row.center-xs
  .col-xs-11
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Nombre
            %th Id Crédito
            %th Id Socio
            %th Id Juicio
            %th Cédula
            %th Etapa Actual
            %th Actividad
            %th Etapa Estimada
            %th Estado
            %th Semaforo
            %th Ver
            %th
        %tbody
          - @insolvencias.each do |trial|
            - semaforos = trial.semaforo
            %tr
              %td= trial.nombres
              %td= trial.credit_id
              %td= trial.socio_id
              %td= trial.juicio_id
              %td= trial.cedula
              %td= best_in_place_if(trial.user == current_user,trial, :insolvency_stage_id, :as => :select, collection: InsolvencyStage.collection)
              %td= best_in_place_if(trial.user == current_user,trial, :insolvency_activity_id, :as => :select, collection: trial.insolvency_stage.get_activities)
              %td= trial.etapa_estimada
              %td= trial.estado
              %td
                %span.label{class: "#{semaforos[1]}"}
                  = semaforos[0]
              %td= link_to "Ver", insolvency_path(trial), class: "btn btn-inverse"